### ISSUE TITLE
#10 in the quiz for Program with Expressions is broken

### ISSUE THREAD

**Issue by victoriagrows-xx** [learn-co-curriculum/prework-intro-navigating-curriculum-on-learn-ide#1]
In the quiz for #10 This is not a valid expression. "The expression below evaluates to: 3 + 6 (2)"

You're missing the * character here:
"The expression below evaluates to: 3 + 6 * (2)", or the problem is missed.

**Comment by maxwellbenton** [comment]
Hi @victoriagrows,

Thank you for spotting this and providing feedback. We've updated this quiz question (added the missing *) so that the expression is valid and evaluates to the expected quiz answer.

The lesson should display with the correct expression for future students. Thank you for contributing to a Learn.co lesson!
